Repository AY2324S2-CS2103T-T12-2/tp, pull requests merged in 2024-03, with the labels that each got.

#43 v1.2 RemoveCommand Feature
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
Labels: priority.High

#44 v1.2 FilterCommand by tag
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.High, type.Task

#75 Add fuzzy package which includes functions used for fuzzy matching wh…
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/fuzzy/BkTreeCommandMatcher.java
  src/main/java/seedu/address/logic/parser/fuzzy/BkTreeNode.java
  src/main/java/seedu/address/logic/parser/fuzzy/CommandMatcher.java
  src/main/java/seedu/address/logic/parser/fuzzy/DistanceFunction.java
  src/main/java/seedu/address/logic/parser/fuzzy/FuzzyCommandParser.java
  src/main/java/seedu/address/logic/parser/fuzzy/LevenshteinDistance.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: enhancement, priority.High

#74 Add Input Navigation using Up/Down Keys
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/ExitWindow.java
  src/main/resources/view/CommandBox.fxml
Labels: enhancement, priority.High

#80 Uml diagrams
  docs/DeveloperGuide.md
  docs/diagrams/FuzzyInputClassDiagram.puml
  docs/diagrams/FuzzyInputObjectDiagram.puml
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/SortCommandSequenceDiagram.jpg
Labels: documentation

#83 Updated DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#81 Bug Fix and Assertion Statements
  src/main/java/seedu/address/ui/CommandBox.java
Labels: bug, code.quality

#91 v1.3 Copy Function of Contacts
  src/main/java/seedu/address/AddCommandHelper.java
  src/main/java/seedu/address/logic/commands/CopyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CopyCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/fuzzy/FuzzyCommandParser.java
Labels: type.features
