Repository AY2324S2-CS2103T-T12-2/tp, pull requests merged in 2024-04, with the labels that each got.

#97 Ug update
  docs/UserGuide.md
  docs/images/AddByStep.png
  docs/images/Ui-help.png
  docs/images/Ui.png
  docs/images/confirmation.png
  docs/images/duplicate-command.png
  docs/images/duplicate-success.png
  docs/images/error.png
  docs/images/example.png
  docs/images/index-remove.png
  docs/images/no-confirm.png
  docs/images/no-result.png
  docs/images/recovered.png
  docs/images/remove-index.png
  docs/images/remove.png
  docs/images/sample.png
  docs/images/undo.png
  docs/images/yes-confirm.png
  docs/images/yes-result.png
Labels: documentation

#98 Edited UserGuide.md
  docs/UserGuide.md
Labels: documentation

#165 Fixed bugs for Overwrite command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/OverwriteCommand.java
  src/main/java/seedu/address/logic/parser/OverwriteCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: bug

#168 Ug update and Fuzzy Input debug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/fuzzy/FuzzyCommandParser.java
Labels: bug

#177 Remove first part of RemoveCommand feature (partial feature removal)
  docs/UserGuide.md
  docs/images/confirmation.png
  docs/images/index-remove.png
  docs/images/no-confirm.png
  docs/images/no-result.png
  docs/images/yes-confirm.png
  docs/images/yes-result.png
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
Labels: priority.High, type.Bug, must_fix

#185 Undo Documentation Bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: bug, documentation

#196 Branch v1.4 dg update - diagrams
  docs/DeveloperGuide.md
  docs/diagrams/RemoveConfirmationClassDiagram.puml
  docs/diagrams/RemoveConfirmationSequenceDiagram.puml
  docs/diagrams/RemoveSequenceDiagram.puml
  docs/diagrams/SafeRemovalActivityDiagram.puml
Labels: documentation
